# Generated by Django 5.1.3 on 2026-06-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_color',
            field=models.CharField(default='#10b981', max_length=7),
        ),
    ]
